"""
spiraldill/biology_galois.py — Galois structure of biology's substrate.

Computes Frobenius orbits on GF(64) = GF(4)^3 = codon space.

The framework's biological substrate is GF(4) (CONVERGENCES §5.10). Codon space
is GF(64) ≅ GF(4)³. The Galois group Gal(GF(64)/GF(4)) = Z/3Z is generated by
Frobenius σ: x ↦ x^4.

The three-fold structure of fermion generations may correspond to this rigid
3-fold Galois orbit structure. This module provides the computational content
for that investigation — the structural facts are FORCED by Galois theory;
the correspondence to physics is open.

Construction:
    GF(64) = GF(2)[γ] / (γ^6 + γ + 1)
    Elements: integers 0..63 with bit i = coefficient of γ^i.
    Multiplication: polynomial multiplication over GF(2), reduce by γ^6 = γ + 1.

Frobenius:
    σ(x) = x^4 has order 3 on GF(64) (since [GF(64):GF(4)] = 3).
    Orbits: 4 of size 1 (= GF(4) fixed points) + 20 of size 3 = 24 total orbits.
"""

from __future__ import annotations
from typing import Iterator


# ============================================================
# GF(64) arithmetic
# ============================================================

# Reduction polynomial: γ^6 = γ + 1, i.e., reduce by XOR with bits {6, 1, 0}.
# In integer form: 0b1000011 = 67. When the degree-6 coefficient appears,
# we XOR with this value to replace γ^6 with (γ + 1).

GF64_REDUCTION = 0b1000011  # represents γ^6 + γ + 1 = 0


def gf64_mul(a: int, b: int) -> int:
    """Multiply two elements of GF(64) represented as 6-bit integers."""
    result = 0
    while b > 0:
        if b & 1:
            result ^= a
        b >>= 1
        a <<= 1
        if a & (1 << 6):  # degree-6 term appears; reduce
            a ^= GF64_REDUCTION
    return result


def gf64_pow(a: int, n: int) -> int:
    """Compute a^n in GF(64) via square-and-multiply."""
    result = 1
    base = a
    while n > 0:
        if n & 1:
            result = gf64_mul(result, base)
        base = gf64_mul(base, base)
        n >>= 1
    return result


def frobenius(x: int) -> int:
    """Apply Frobenius automorphism σ: x ↦ x^4."""
    return gf64_pow(x, 4)


# ============================================================
# Orbit computation
# ============================================================

def frobenius_orbit(x: int) -> list[int]:
    """Compute the Frobenius orbit of x ∈ GF(64)."""
    orbit = [x]
    y = frobenius(x)
    while y != x:
        orbit.append(y)
        y = frobenius(y)
    return orbit


def all_orbits() -> list[list[int]]:
    """Compute all Frobenius orbits on GF(64)."""
    orbits: list[list[int]] = []
    visited: set[int] = set()
    for x in range(64):
        if x in visited:
            continue
        orbit = frobenius_orbit(x)
        orbits.append(orbit)
        visited.update(orbit)
    return orbits


def gf4_elements() -> list[int]:
    """Return the GF(4) elements as embedded in GF(64) (the Frobenius fixed points)."""
    return [x for x in range(64) if frobenius(x) == x]


def orbit_size_distribution() -> dict[int, int]:
    """Count orbits by size. Should be {1: 4, 3: 20}."""
    orbits = all_orbits()
    distribution: dict[int, int] = {}
    for orbit in orbits:
        size = len(orbit)
        distribution[size] = distribution.get(size, 0) + 1
    return distribution


# ============================================================
# Verification
# ============================================================

def verify_galois_structure() -> dict:
    """Verify the Z/3Z Galois orbit structure on GF(64).
    
    Returns a dict with verification facts. All facts are FORCED by Galois theory
    of the GF(64)/GF(4) extension.
    """
    orbits = all_orbits()
    fixed = gf4_elements()
    distribution = orbit_size_distribution()
    
    # The fixed points of Frobenius form GF(4) — verify there are exactly 4
    assert len(fixed) == 4, f"Expected 4 GF(4) elements, got {len(fixed)}"
    
    # Total elements should be 64
    total = sum(len(o) for o in orbits)
    assert total == 64, f"Expected 64 elements total, got {total}"
    
    # Orbit sizes should divide |Gal(GF(64)/GF(4))| = 3
    for orbit in orbits:
        assert len(orbit) in {1, 3}, f"Unexpected orbit size: {len(orbit)}"
    
    # Number of size-3 orbits should be (64 - 4) / 3 = 20
    size_3_count = distribution.get(3, 0)
    assert size_3_count == 20, f"Expected 20 orbits of size 3, got {size_3_count}"
    
    # The galois group order = field extension degree = 3
    galois_order = 3
    field_extension_degree = 3  # [GF(64) : GF(4)]
    assert galois_order == field_extension_degree
    
    return {
        "framework_claim": "Three-fold Galois structure on biology's substrate",
        "construction": "GF(64) = GF(2)[γ]/(γ^6 + γ + 1), or equivalently GF(4)³ codon space",
        "galois_group": "Gal(GF(64)/GF(4)) = Z/3Z",
        "frobenius_generator": "σ: x ↦ x^4",
        "field_extension_degree": field_extension_degree,
        "total_orbits": len(orbits),
        "fixed_points_count": len(fixed),
        "fixed_points_constitute": "GF(4) embedded in GF(64)",
        "size_3_orbits_count": size_3_count,
        "verification": "PASSED — Z/3Z structure verified",
        "structural_count_match": {
            "claim": "Number of fermion generations = 3",
            "structural_basis": "[GF(64) : GF(4)] = 3 = order of Galois group",
            "status": "structural count match FORCED by Galois theory",
            "physics_correspondence": "OPEN — mapping from Galois orbits to specific SM fermion content not yet derived"
        }
    }


if __name__ == "__main__":
    print("=" * 72)
    print("BIOLOGY GALOIS — Frobenius orbit structure of GF(64)/GF(4)")
    print("=" * 72)
    print()
    
    result = verify_galois_structure()
    
    print(f"Framework claim: {result['framework_claim']}")
    print(f"Construction:    {result['construction']}")
    print(f"Galois group:    {result['galois_group']}")
    print(f"Generator:       {result['frobenius_generator']}")
    print(f"Extension degree: [GF(64):GF(4)] = {result['field_extension_degree']}")
    print()
    print(f"Orbit structure:")
    print(f"  Total orbits:        {result['total_orbits']}")
    print(f"  Fixed points (GF(4)): {result['fixed_points_count']}")
    print(f"  Size-3 orbits:       {result['size_3_orbits_count']}")
    print()
    
    print(f"Sample orbits of size 3 (first 6):")
    orbits = all_orbits()
    size_3 = [o for o in orbits if len(o) == 3]
    for o in size_3[:6]:
        print(f"  {sorted(o)}")
    print()
    
    print(f"GF(4) elements (Frobenius fixed points): {sorted(gf4_elements())}")
    print()
    
    scm = result['structural_count_match']
    print(f"Structural count match:")
    print(f"  Claim:              {scm['claim']}")
    print(f"  Structural basis:   {scm['structural_basis']}")
    print(f"  Status:             {scm['status']}")
    print(f"  Physics open:       {scm['physics_correspondence']}")
    print()
    print(f"Verification: {result['verification']}")
